steps:
  # Build React app
  - name: 'node:18'
    entrypoint: npm
    args: ['install']
    dir: '.'
  
  - name: 'node:18'
    entrypoint: npm
    args: ['run', 'build']
    dir: '.'
  
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/news-crawler', '.']
  
  # Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/news-crawler']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'news-crawler'
      - '--image'
      - 'gcr.io/$PROJECT_ID/news-crawler'
      - '--region'
      - 'asia-northeast3'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'BIGKINDS_KEY=${_BIGKINDS_KEY}'

images:
  - 'gcr.io/$PROJECT_ID/news-crawler'